### ISSUE TITLE
Login form "login" button doesn't re-enable after a failed login attempt

### ISSUE THREAD

**Issue by nanaewusi** [fermislab/apartment#10]
@yawboakye: After providing bad credentials, the login button gets disabled and you get the proper feedback about what you did wrong. However, the button doesn't get re-enabled even after you've made changes to your earlier inputs (email/password). See screenshot below:

![screen shot 2016-04-04 at 12 12 48 am 2](https://cloud.githubusercontent.com/assets/3534919/14235890/70e11c7e-f9fa-11e5-8bc2-c550024ce641.png)

**Comment by yawboakye** [comment]
Seen. Can you investigate and submit a fix? I've got a lot on my hands already. Thanks
